services:
  trino:
    image: trinodb/trino:466
    hostname: trino
    container_name: trino
    networks:
      - metastore-default
      - minio_default
      - mongo_default
    ports:
      - 18010:18010
    volumes:
      - ./etc:/etc/trino
    healthcheck:
      test: curl -f localhost:18010
      interval: 3s
      timeout: 2s
      retries: 10
networks:
  metastore-default:
    external: true
  minio_default:
    external: true
  mongo_default:
    external: true
