services:
  sr:
    image: starrocks/allin1-ubuntu:3.2.12
    hostname: sr
    container_name: sr
    networks:
      - sr_default
      - metastore-default
      - minio_default
    ports:
      - 9030:9030
      - 8030:8030
      - 8040:8040
    healthcheck:
      test: nc -zv localhost 9030
      interval: 3s
      timeout: 2s
      retries: 10
networks:
  sr_default:
    name: sr_default
    external: false
  metastore-default:
    external: true
  minio_default:
    external: true
