services:
  metastore-db:
    image: mysql:8.0.23
    restart: always
    networks:
      - minio1_default
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: metastore_db
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive123
    healthcheck:
      test: mysql -proot123 -e 'select 1'
      interval: 5s
      timeout: 3s
      retries: 10
  metastore-1:
    image: archongum/hive:4.0.1
    restart: always
    networks:
      - minio1_default
    ports:
      - 19083:9083
    depends_on:
      metastore-db:
        condition: service_healthy
    volumes:
      - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf/metastore-site.xml:/opt/hive/conf/metastore-site.xml
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: mysql
      SERVICE_OPTS: "-Xmx2G"
  metastore-2:
    image: archongum/hive:4.0.1
    restart: always
    networks:
      - minio1_default
    ports:
      - 19084:9083
    depends_on:
      metastore-db:
        condition: service_healthy
    volumes:
      - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf/metastore-site.xml:/opt/hive/conf/metastore-site.xml
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: mysql
      SERVICE_OPTS: "-Xmx2G"
networks:
  minio1_default:
    external: true
