x-service-templates:
  template_metastore: &template_metastore
    image: archongum/hive:4.0.1
    restart: always
    networks:
      - metastore-default
      - mysql_default
      - minio_default
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: mysql
      SERVICE_OPTS: "-Xmx1G"
    healthcheck:
      test: netstat -ln | grep 9083
      interval: 3s
      timeout: 2s
      retries: 10
services:
  # MetaStone 1 (HA)
  metastore1-ha1:
    <<: *template_metastore
    hostname: metastore1-ha1
    container_name: metastore1-ha1
    volumes:
      - ./conf1/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf1/metastore-site.xml:/opt/hive/conf/metastore-site.xml
  metastore1-ha2:
    <<: *template_metastore
    hostname: metastore1-ha2
    container_name: metastore1-ha2
    volumes:
      - ./conf1/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf1/metastore-site.xml:/opt/hive/conf/metastore-site.xml
  # MetaStone 2 (HA)
  metastore2-ha1:
    <<: *template_metastore
    hostname: metastore2-ha1
    container_name: metastore2-ha1
    volumes:
      - ./conf2/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf2/metastore-site.xml:/opt/hive/conf/metastore-site.xml
  metastore2-ha2:
    <<: *template_metastore
    hostname: metastore2-ha2
    container_name: metastore2-ha2
    volumes:
      - ./conf2/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf2/metastore-site.xml:/opt/hive/conf/metastore-site.xml
networks:
  # StarRocks changed 'thrift://metastore1-ha1:9083' to 'thrift://metastore1-ha1.metastore_default:9083'
  # then throws 'Illegal character in hostname'
  # so use '-' instead of '_'
  metastore-default:
    name: metastore-default
    external: false
  mysql_default:
    external: true
  minio_default:
    external: true
