x-service-templates:
  template_metastore: &template_metastore
    image: archongum/hive:4.0.1
    restart: always
    networks:
      - mysql_default
      - minio_default
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: mysql
      SERVICE_OPTS: "-Xmx1G"
    healthcheck:
      test: netstat -ln | grep 9083
      interval: 3s
      timeout: 2s
      retries: 10
services:
  # MetaStone 1 (HA)
  metastore1_ha1:
    <<: *template_metastore
    ports:
      - 19083:9083
    volumes:
      - ./conf1/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf1/metastore-site.xml:/opt/hive/conf/metastore-site.xml
  metastore1_ha2:
    <<: *template_metastore
    ports:
      - 19084:9083
    volumes:
      - ./conf1/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf1/metastore-site.xml:/opt/hive/conf/metastore-site.xml
  # MetaStone 2 (HA)
  metastore2_ha1:
    <<: *template_metastore
    ports:
      - 29083:9083
    volumes:
      - ./conf2/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf2/metastore-site.xml:/opt/hive/conf/metastore-site.xml
  metastore2_ha2:
    <<: *template_metastore
    ports:
      - 29084:9083
    volumes:
      - ./conf2/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf2/metastore-site.xml:/opt/hive/conf/metastore-site.xml
networks:
  mysql_default:
    external: true
  minio_default:
    external: true
